@baseURL = http://localhost:3000
@catServiceURL = {{baseURL}}/rest/v1/catalog
@adminServiceURL = {{baseURL}}/rest/v1/admin
@authentication = Basic alice:secret

### get root
GET {{baseURL}}/
Authorization: {{authentication}}


### get Books
GET {{catServiceURL}}/Books
Authorization: {{authentication}}


### post Books
POST {{adminServiceURL}}/Books
Authorization: {{authentication}}
Content-Type: application/json

{
    "ID"  : 666,
    "title": "Satan bible",
    "author_ID": 666,
    "genre_ID": 666,
    "stock":666
}

### delete Books (not so OData style)
DELETE {{adminServiceURL}}/Books
Authorization: {{authentication}}
Content-Type: application/json

{
    "id"  : 666
}