@baseURL = http://localhost:3000
@catServiceURL = {{baseURL}}/rest/v1/catalog
@adminServiceURL = {{baseURL}}/rest/v1/admin
@authentication = Basic alice:secret

### get root
GET {{catServiceURL}}/
Authorization: {{authentication}}


### get metadata
GET {{catServiceURL}}/$metadata
Authorization: {{authentication}}


### get Books
GET {{catServiceURL}}/Books
Authorization: {{authentication}}


### get Books in some more interesting ways
GET {{catServiceURL}}/Books?$select=title&$filter=ID ne 666&$expand=genre
Authorization: {{authentication}}


### post $batch
@body = --batch_id_123\r\nContent-Type:application/http\r\nContent-Transfer-Encoding:binary\r\n\r\nPATCH Books(ID=666) HTTP/1.1\r\nAccept:application/json\r\nAccept-Language:en\r\nContent-Type:application/json\r\n\r\n{"title":"Holy Bible"}\r\n--batch_id_123\r\nContent-Type:application/http\r\nContent-Transfer-Encoding:binary\r\n\r\nGET Books(666) HTTP/1.1\r\nAccept:application/json\r\nAccept-Language:en\r\nContent-Type:application/json\r\n\r\n\r\n--batch_id_123--
POST {{catServiceURL}}/$batch
Authorization: {{authentication}}
Content-Type: multipart/mixed; boundary=batch_id_123

{{body}}


### call ubound submitOrder action
POST {{catServiceURL}}/submitOrder
Authorization: {{authentication}}
Content-Type: application/json

{
    "book": 666, 
    "quantity": 666
}


### call bound draftEdit action
POST {{adminServiceURL}}/Books(ID=666)/AdminService.addRating
Authorization: {{authentication}}
Content-Type: application/json
        
{
    "stars": 666
}


### get Book 666
GET {{adminServiceURL}}/Books/666
Authorization: {{authentication}}


### post Books
POST {{adminServiceURL}}/Books
Authorization: {{authentication}}
Content-Type: application/json

{
    "ID"  : 666,
    "title": "Satan bible",
    "author_ID": 666,
    "genre_ID": 666,
    "stock":666
}

### delete Books (not so OData style)
DELETE {{adminServiceURL}}/Books
Authorization: {{authentication}}
Content-Type: application/json

{
    "id"  : 666
}