@baseURL = http://localhost:3000
@catServiceURL = {{baseURL}}/odata/v4/catalog
@adminServiceURL = {{baseURL}}/odata/v4/admin
@authentication = Basic alice:secret

### get catalog $metadata
GET {{catServiceURL}}/$metadata
Authorization: {{authentication}}


### get admin $metadata
GET {{adminServiceURL}}/$metadata
Authorization: {{authentication}}


### get catalog Books
GET {{catServiceURL}}/Books
Authorization: {{authentication}}


### create author
@date = {{ $datetime 'YYYY-MM-DD' 1 d }}
POST {{adminServiceURL}}/Authors
Authorization: {{authentication}}
Content-Type: application/json

{
    "ID"  : 666,
    "name": "Satan",
    "dateOfBirth" : "{{date}}"
}


### create genre
POST {{adminServiceURL}}/Genres
Authorization: {{authentication}}
Content-Type: application/json

{
    "ID"  : 666,
    "parent_ID": null,
    "name": "Holy books",
    "descr": "Can be highly opinionated"
}


### create book
POST {{adminServiceURL}}/Books
Authorization: {{authentication}}
Content-Type: application/json

{
    "ID"  : 666,
    "title": "Satan bible",
    "author_ID": 666,
    "genre_ID": 666,
    "stock":666
}


### get Book 666 with expands - expanded object is a string!
GET {{catServiceURL}}/Books(666)?$select=title,author&$expand=genre
Authorization: {{authentication}}


### delete book
DELETE {{adminServiceURL}}/Books(666)
Authorization: {{authentication}}